### ISSUE TITLE
Please add license information

### ISSUE THREAD

**Issue by DonOregano** [keyboardio/Arduino-Boards#1]
Please add a COPYING or LICENSE file in the root of all the keyboardio repos that specifies the license(s) of the code in the repo.

**Comment by algernon** [comment]
There are a number of different licenses used by this repo directly. I'll go through them and submit a PR with my findings.

Question to @obra: What license do you want for `boards.txt` and `platforms.txt`? And what about the small scripts all around the place? I'd suppose either GPLv3 or LGPLv3 would work?

**Comment by obra** [comment]
boards.txt and platforms.txt really don't feel like they ought to be copyrightable, but since ours are based on the Arduino versions and the arduino license.txt states: "next, the gnu lesser general public license that covers the arduino core and libraries." and includes a copy of the LGPL v2.1. Given that the LGPL is more permissive than the GPL, I think I'd opt not to take advantage of the LGPL's provisions for converting LGPL code to GPL code for boards.txt and platforms.txt. -- so stick with LGPL there.

Our build tooling is not strictly part of the firmware itself. For the tooling scripts, I'm probably more comfortable with the MIT license or something equally permissive. I've been on the other side of needing the functionality of a small shell script and having it licensed in such a way that I needed to rewrite it. None of the infrastructure or automation is secret sauce and I'd rather just let people take them.

**Comment by DonOregano** [comment]
Yeah, the reason I raised this issue is that it becomes relevant when packaging software. It just feels better when software has clear license statements.

**Comment by DonOregano** [comment]
Any progress?

**Comment by obra** [comment]
A fair bit, actually. We've split out just about all of the _code_ that was
in this repo into subrepositories. This repo is, essentially a
distribution, so slapping a top-level license on it is going to be a lot
more misleading than helpful.

At this point, the only things _in_ this repo are:

* derivatives of the arduino pins.h, which has license information
* derivatives of the arduino boards.txt and platform.txt, which are
configuration files, not code.
* a trivial Makefile used for administrative purposes.
* travis and git configuration
* a readme

Yes, we still have work to do. Given the above, I'd love to hear your
feeling on the right way to handle the remaining tasks.
